"""Fetches and reads the court-generated Order document for a granted motion.

Unlike the Foreclosure Worksheet (a filer-completed, scanned form), the
Order is generated by the court's own case management system -- confirmed
on a real filing to be clean, consistently-formatted, computer-typeset
text (not handwritten, not a scanned paper form), which OCRs far more
reliably. A real granted strict-foreclosure Order reads like:

    MOTION FOR STRICT FORECLOSURE IS GRANTED
    Debt:$ 183,134.81
    Fair Market Value:$ 110,000.00
    Counsel Fee:$ 2525.00
    Appraiser Fee:$ 300.00
    Title Fee:$225.00
    Law Day:2/4/2019, for the owner of equity of redemption...

A foreclosure-by-sale Order states "Sale Date:" instead of "Law Day:".
This is the only reliable source found for that date -- it does not
appear in the docket entry text itself, only inside the Order PDF.

The Order entry's numbering relative to its motion is not consistent
across cases (".86" suffix, ".10", sometimes a ".20" correction of an
earlier ".10" mistake) -- see find_order_entry() below, which locates it
by scanning nearby entries instead of assuming a fixed offset.
"""

import re
from datetime import date

from playwright.async_api import BrowserContext

from .models import DocketEntry
from .motions import is_order_entry
from .throttle import Throttle
from .worksheet import fetch_worksheet_pdf, render_first_page

import pytesseract

# Two Order-document templates confirmed on real filings, each with
# different date phrasing: "Law Day:2/4/2019" (numeric, no space) vs. "The
# Sale Date is: Saturday, April 25, 2026" (spelled-out month, with a
# weekday name in between the label and the date). _DATE_ANY matches
# either a numeric M/D/YYYY date or a "Month D, YYYY" one.
_DATE_ANY = r"(\d{1,2}/\d{1,2}/\d{2,4}|[A-Za-z]+\s+\d{1,2},?\s+\d{4})"
KEY_DATE_PATTERNS = [
    ("Law Day", re.compile(rf"Law\s*Day\s*(?:is)?\s*:?\s*(?:\w+,\s*)?{_DATE_ANY}", re.I)),
    ("Sale Date", re.compile(rf"Sale\s*Date\s*(?:is)?\s*:?\s*(?:\w+,\s*)?{_DATE_ANY}", re.I)),
]

BANKRUPTCY_CHAPTER_PATTERN = re.compile(r"Chapter\s+(7|11|12|13)\b", re.I)


def _entry_prefix(entry_no: str) -> str | None:
    m = re.match(r"^(\d+)", entry_no.strip())
    return m.group(1) if m else None


def find_order_entry(entries: list[DocketEntry], anchor: DocketEntry) -> DocketEntry | None:
    """Find the ORDER entry associated with a given motion entry.

    Candidates are entries sharing the same integer entry-number prefix
    (e.g. "111.00" -> "111.10", "111.20", "111.86" are all candidates for
    anchor "111.00") whose description is itself literally an ORDER entry.
    When a motion's order was corrected (an erroneous ".10" superseded by
    a ".20"), the latest-filed one is authoritative, so ties are broken by
    file date, latest first.
    """
    prefix = _entry_prefix(anchor.entry_no)
    if prefix is None:
        return None
    candidates = [
        e for e in entries
        if e is not anchor and _entry_prefix(e.entry_no) == prefix and is_order_entry(e.description)
    ]
    if not candidates:
        return None

    def _date_key(e: DocketEntry):
        try:
            from datetime import datetime
            return datetime.strptime(e.file_date.strip(), "%m/%d/%Y")
        except ValueError:
            return datetime.min

    return max(candidates, key=_date_key)


async def fetch_document_text(context: BrowserContext, throttle: Throttle, document_url: str) -> str:
    await throttle.wait()
    resp = await context.request.get(document_url, timeout=30000)
    pdf_bytes = await resp.body()
    image = render_first_page(pdf_bytes)
    return pytesseract.image_to_string(image)


def _parse_date(raw: str) -> date | None:
    from datetime import datetime
    raw = raw.strip().rstrip(",")
    for fmt in ("%m/%d/%Y", "%m/%d/%y", "%B %d, %Y", "%B %d %Y"):
        try:
            return datetime.strptime(raw, fmt).date()
        except ValueError:
            continue
    return None


def extract_key_date(text: str) -> tuple[date | None, str | None]:
    """Extract Law Day or Sale Date from an Order document's OCR text.

    Returns (date, label) -- label is "Law Day" or "Sale Date", whichever
    pattern actually matched, not guessed separately from the date.
    """
    for label, pattern in KEY_DATE_PATTERNS:
        m = pattern.search(text)
        if m:
            parsed = _parse_date(m.group(1))
            if parsed:
                return parsed, label
    return None, None


def extract_bankruptcy_chapter(text: str) -> str | None:
    m = BANKRUPTCY_CHAPTER_PATTERN.search(text)
    return m.group(1) if m else None


DENIED_PATTERN = re.compile(r"\bDENIED\b", re.I)
GRANTED_PATTERN = re.compile(r"\bGRANTED\b", re.I)
HEREBY_ENTERED_PATTERN = re.compile(r"HEREBY\s+ENTERED", re.I)


def is_order_granted(text: str) -> bool:
    """Whether an Order document reflects a granted (not denied) judgment.

    Confirmed on real filings that Order documents use at least two
    different templates for a granted judgment: one literally says
    "MOTION FOR STRICT FORECLOSURE IS GRANTED"; another says only
    "ORDER:" followed directly by "Judgment of Foreclosure by Sale is
    hereby entered as follows: ..." with no literal "GRANTED" anywhere.
    Checking for "DENIED" first (which does appear literally when a
    motion is denied) avoids a false positive from the word "GRANTED"
    appearing in some unrelated context; the presence of a key date
    (Law Day / Sale Date) is also treated as evidence of a granted
    judgment, since a denial order has no reason to state one.
    """
    if DENIED_PATTERN.search(text):
        return False
    if GRANTED_PATTERN.search(text) or HEREBY_ENTERED_PATTERN.search(text):
        return True
    key_date, _ = extract_key_date(text)
    return key_date is not None
